server:
  port: 8686
# DataSource Config
spring:
  datasource:
    #druid相关配置
    type: com.alibaba.druid.pool.DruidDataSource
    #监控统计拦截的filters
    filter:
      stat:
        enabled: true
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 2000
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'stocks'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    driverClassName: com.mysql.cj.jdbc.Driver
    #配置基本属性
    url: jdbc:mysql://localhost:3306/future?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: linjingu
    password: linjingu
    #配置初始化大小/最小/最大
    initialSize: 10
    minIdle: 10
    maxActive: 30
  # 单机配置，启动：redis-server /Users/ruian/etc/redis.conf &
  redis:
    host: localhost
    port: 6379
    database: 0
    password: admin
    pool:
      connectionMinimumIdleSize: 10
      # 连接池最大连接数（使用负值表示没有限制）
      maxactive: 64
      # 连接池中的最大空闲连接
      maxidle: 64
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxwait: -1
      # 连接池中的最小空闲连接
      minidle: 1
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 649054380@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: kezmbmzrjexobefg
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
mybatis:
  mapper-locations: classpath:mapping/*DAO.xml

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

future:


